name: simple_redux
description: Another implementation of Redux pattern.
version: 0.0.1
homepage: https://github.com/mponkin/simple_redux
author: mikhail.ponkin <mponkin@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
