name: simple_redux
description: Another implementation of Redux pattern. Inspired by https://jayrambhia.com/blog/android-redux-intro
version: 0.1.0+1
homepage: https://github.com/mponkin/simple_redux
author: Mikhail Ponkin <mponkin@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

#dev_dependencies:
#  test: ^1.0.0
